version = 1
disable_existing_loggers = true

[formatters.error]
format = '%(asctime)s - %(levelname)s - %(name)s - %(process)s - %(module)s - %(filename)s - %(funcName)s - %(lineno)d - %(message)s'

[handlers.info_rotating_file_handler]
level = 'INFO'
formatter = 'error'
class = 'logging.handlers.RotatingFileHandler'
filename = 'info.log'
mode = 'a'
maxBytes = 1048576
backupCount = 0

[loggers.'']
handlers = ['info_rotating_file_handler']
level = 'INFO'
propagate = true
